if: branch = master OR branch = develop
language: java
jdk:
 - oraclejdk8
services:
  - docker
notifications:
  email: false
addons:
  sonarcloud:
    organization: "blahami2-github"
    token:
      secure: "aP4tyVSrKVw2DIhRV6fR+88wM9VP5HgJvBHgzufHrfyeoaVZYqy/80ZxtMtkHJ3Fq7jEr7H6V/rbTv6tY/s9LLDr4JOTG5pnTfKrbDrvRzOL/KD1/nSL4s0CEeeL668kmYI6S3fwSSYECW/ojExCFCiELcGUtyGiqy/oMRf5pgJkBCLYTKc36ogD/j9VcVDypYpPC+Rhny2ZysOwi2nHu1eMkRDHC+EaHXDp2WBfAl605xwEUAz9RjS+bbg9mkY+uQIJbdUvIqjbo4b0Ipa7xcXC6KV9H3DA9eGiEb537UwAs+hdcDHK4VXE5aQmcdTo711IK7bt617lQXaCcJduDAR04vEPim04/OYye6wwxtwYtlXJvf/JF0a/9XYRkaD8R2LDhhCNk73+lEvKZ/V1FO4Mx/2+eA6AA6ahYWz7uFi0ezHfNMUFGlqHC2FDEDzurefRsFBfHfTOzZP1R4M/G5AD5gG0GqkucZAOyU1OCWJ0QKKJcz36BRaG2h34W2qn90YHB/kW53ULxjHlGl61iR4qX9MdswcxsCgUtyTLmxqvoo/WjiaCup3fxdExZAYUPOS5J6ViOhL8xFrvaBZTWRzR+pHbQaQJNnhh14xuQS0iEmAEyS0X7IXjlLFF45R4bpkw93b9LwNi7LecNB526SDU6h1a1EVQ18eXYAElj/0="
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
deploy:
  - provider: heroku
    api_key:
      secure: "cs1Hl8Q05z9RykcXfC8wX2eEEilghh1EMMXJcDJZFKAVyuXhqzDkmC1+41MNyOHx+oaNe05CIqOa+UvDYrGRF0bK60muqQZtDsA70AyLlxy34jOEcMDIOk9SdvUrHrujb5BkaCkYOYEtihU4bzFY7gjgCkTlEgdmFHCIaNVY2/PtGt0asydpG+7IxTFJ5/F2s9x5vfVuRU41WPN71656BOjF2u+GHUn3TlTrdcaSbUwY8UnCRMnNu6nWjrhO1dWfnnnXCEVDOxWjl/C3+T/g6P3KT61m0qsCFrCwzf2Mcx071LmJtRUp7uqjErcZfKr2YJgXZYzjd+pExUqsbAO/HJPkhKEGvudrk3aBdS4Ir7iCKS/z67RO+tZzAsizdSu09tZ9DzOBK7g0BMhVMnKenu6bWijToH6IluaDEx5lq6eHs9TGj6VWRTLUzpTBtTxS7EaVwkNqBbBVfXzUc9f/D1S3zk4OXdBP/VLbPhEsUogQJKVjo3LkIcttOmaa1rib0j4aX+0+ayGAKbwPKa2uos7UDtcnCJpQ4X9METqaUjwJi2M3Q4QlX2kgF3005DCPNnOLlezonXWPMssY5t2z8Wlpgh22YdJ4nyb//i8tfiOU06oEsXHlS/l1wjYtq77fWoavi+uSKd3ywXDOHmp/kXqfqAlKR9iY329YDW8Q05c="
    on:
      branch: master